defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "index"
  _editor:
    default_path: /about/
#
site-text-direction: "lt-ie10"
#
brand: "e-Smartz"
website-type: "MegaFreight"
og-type: "IT Consulting, Development and Support"
social-image: ""
#
